version: '3.8'
services:
  app:
    build: ..
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/namaste_fhir
      - ELASTICSEARCH_URL=http://es:9200
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - db
      - es
      - redis
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=namaste_fhir
    ports:
      - "5432:5432"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
